repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8

- repo: local
  hooks:
    - id: run-coverage
      name: run-coverage
      entry: bash -c "coverage run --omit '*/site-packages/*','*/test/*' -m pytest && coverage report -m"
      language: system
      types: [python]
      pass_filenames: false
      verbose: true
